### ISSUE TITLE
Add background images to content headers

### ISSUE THREAD

**Issue by thewilkybarkid** [libero/publisher#138]
Content headers need to be able to have background images:

<img width="1128" alt="Screenshot 2019-04-17 at 08 20 17" src="https://user-images.githubusercontent.com/1784740/56268634-bdd4d800-60e9-11e9-849b-5cd31dcd20d6.png">

## Tasks

- [x] Add to content header pattern (https://github.com/libero/pattern-library/pull/124)
  - [x] Supports multiple formats
  - [x] Supports multiple sizes
- [x] Add to the homepage on Browser (https://github.com/libero/browser/pull/107)
  - [x] Supports multiple formats
  - [x] Supports multiple sizes
- [x] Add to the unstable environment (https://github.com/libero/sample-configuration/pull/78)

## Notes

- I'm not separating the template and styles.
- eLife uses a variety of sizes and formats:
    ```html
    <picture>
        <source srcset="https://iiif.elifesciences.org/journal-cms/podcast_episode%2F2019-02%2F37412-artibeus-watsonii-stephen-rossiter-cc-by-4_fotor.jpg/0,146,1800,1056/900,528/0/default.webp 2x, https://iiif.elifesciences.org/journal-cms/podcast_episode%2F2019-02%2F37412-artibeus-watsonii-stephen-rossiter-cc-by-4_fotor.jpg/0,146,1800,1056/450,264/0/default.webp 1x" type="image/webp" media="(max-width: 450px)">
        <source srcset="https://iiif.elifesciences.org/journal-cms/podcast_episode%2F2019-02%2F37412-artibeus-watsonii-stephen-rossiter-cc-by-4_fotor.jpg/0,146,1800,1056/900,528/0/default.jpg 2x, https://iiif.elifesciences.org/journal-cms/podcast_episode%2F2019-02%2F37412-artibeus-watsonii-stephen-rossiter-cc-by-4_fotor.jpg/0,146,1800,1056/450,264/0/default.jpg 1x" type="image/jpeg" media="(max-width: 450px)">
        <source srcset="https://iiif.elifesciences.org/journal-cms/podcast_episode%2F2019-02%2F37412-artibeus-watsonii-stephen-rossiter-cc-by-4_fotor.jpg/0,348,1800,652/1458,528/0/default.webp 2x, https://iiif.elifesciences.org/journal-cms/podcast_episode%2F2019-02%2F37412-artibeus-watsonii-stephen-rossiter-cc-by-4_fotor.jpg/0,348,1800,652/729,264/0/default.webp 1x" type="image/webp" media="(max-width: 729px)">
        <source srcset="https://iiif.elifesciences.org/journal-cms/podcast_episode%2F2019-02%2F37412-artibeus-watsonii-stephen-rossiter-cc-by-4_fotor.jpg/0,348,1800,652/1458,528/0/default.jpg 2x, https://iiif.elifesciences.org/journal-cms/podcast_episode%2F2019-02%2F37412-artibeus-watsonii-stephen-rossiter-cc-by-4_fotor.jpg/0,348,1800,652/729,264/0/default.jpg 1x" type="image/jpeg" media="(max-width: 729px)">
        <source srcset="https://iiif.elifesciences.org/journal-cms/podcast_episode%2F2019-02%2F37412-artibeus-watsonii-stephen-rossiter-cc-by-4_fotor.jpg/0,386,1800,577/1798,576/0/default.webp 2x, https://iiif.elifesciences.org/journal-cms/podcast_episode%2F2019-02%2F37412-artibeus-watsonii-stephen-rossiter-cc-by-4_fotor.jpg/0,386,1800,577/899,288/0/default.webp 1x" type="image/webp" media="(max-width: 899px)">
        <source srcset="https://iiif.elifesciences.org/journal-cms/podcast_episode%2F2019-02%2F37412-artibeus-watsonii-stephen-rossiter-cc-by-4_fotor.jpg/0,386,1800,577/1798,576/0/default.jpg 2x, https://iiif.elifesciences.org/journal-cms/podcast_episode%2F2019-02%2F37412-artibeus-watsonii-stephen-rossiter-cc-by-4_fotor.jpg/0,386,1800,577/899,288/0/default.jpg 1x" type="image/jpeg" media="(max-width: 899px)">
        <source srcset="https://iiif.elifesciences.org/journal-cms/podcast_episode%2F2019-02%2F37412-artibeus-watsonii-stephen-rossiter-cc-by-4_fotor.jpg/0,378,1800,592/1739,571/0/default.webp 1.7x, https://iiif.elifesciences.org/journal-cms/podcast_episode%2F2019-02%2F37412-artibeus-watsonii-stephen-rossiter-cc-by-4_fotor.jpg/0,378,1800,592/1023,336/0/default.webp 1x" type="image/webp" media="(max-width: 1023px)">
        <source srcset="https://iiif.elifesciences.org/journal-cms/podcast_episode%2F2019-02%2F37412-artibeus-watsonii-stephen-rossiter-cc-by-4_fotor.jpg/0,378,1800,592/1739,571/0/default.jpg 1.7x, https://iiif.elifesciences.org/journal-cms/podcast_episode%2F2019-02%2F37412-artibeus-watsonii-stephen-rossiter-cc-by-4_fotor.jpg/0,378,1800,592/1023,336/0/default.jpg 1x" type="image/jpeg" media="(max-width: 1023px)">
        <source srcset="https://iiif.elifesciences.org/journal-cms/podcast_episode%2F2019-02%2F37412-artibeus-watsonii-stephen-rossiter-cc-by-4_fotor.jpg/0,403,1800,543/1782,537/0/default.webp 1.6x, https://iiif.elifesciences.org/journal-cms/podcast_episode%2F2019-02%2F37412-artibeus-watsonii-stephen-rossiter-cc-by-4_fotor.jpg/0,403,1800,543/1114,336/0/default.webp 1x" type="image/webp">
        <source srcset="https://iiif.elifesciences.org/journal-cms/podcast_episode%2F2019-02%2F37412-artibeus-watsonii-stephen-rossiter-cc-by-4_fotor.jpg/0,403,1800,543/1782,537/0/default.jpg 1.6x, https://iiif.elifesciences.org/journal-cms/podcast_episode%2F2019-02%2F37412-artibeus-watsonii-stephen-rossiter-cc-by-4_fotor.jpg/0,403,1800,543/1114,336/0/default.jpg 1x" type="image/jpeg">
        <img src="https://iiif.elifesciences.org/journal-cms/podcast_episode%2F2019-02%2F37412-artibeus-watsonii-stephen-rossiter-cc-by-4_fotor.jpg/0,403,1800,543/1114,336/0/default.jpg" alt="Picture of the bat Artibeus watsonii">
    </picture>
    ```
  We can't assume that these pictures will have any variants (ie it should work with just a single image).
- Assuming we don't need to include image attribution.

**Comment by chugginselifesciences** [comment]
@Maelplaine We should check IJM have rights to use this image if we are assuming we do not need image attribution

**Comment by Maelplaine** [comment]
Yes Matteo confirmed that this is a CC BY image

**Comment by thewilkybarkid** [comment]
So we need attribution.

**Comment by thewilkybarkid** [comment]
Thinking about it, we don't need attribution until we actually create the IJM site (assuming we don't use an image on the demo environments that also need it!).

**Comment by Maelplaine** [comment]
@thewilkybarkid Yes let's find another image for the demo environment. @chugginselifesciences do you want to find one? I am happy to help

**Comment by chugginselifesciences** [comment]
@Maelplaine I'd been using one of our images by Davide Bonazzi (with an overlay of rbga(0,0,13,0.5)) as it's dark so should be ok with contrast at large font sizes.

But we always attribute to Davide (bottom right) on eLife so would suggest we do it in the same way.
![image](https://user-images.githubusercontent.com/41907215/59751300-30903a00-9278-11e9-94b4-4c47c45e4474.png)

demo:
![image](https://user-images.githubusercontent.com/41907215/59751380-4f8ecc00-9278-11e9-8ba5-dbbc50e2efd4.png)

If we need to avoid attribution I could find a free to use stock photo but they're generally not great.

**Comment by thewilkybarkid** [comment]
I'd like to do attribution as a followup if possible, so if we could find one that's half decent would be ok for the moment?

**Comment by chugginselifesciences** [comment]
Ok - was just mocking this up with attribution so posting anyway for reference:

![image](https://user-images.githubusercontent.com/41907215/59752819-d17ff480-927a-11e9-9e8e-2c88743cdcf0.png)

**Comment by Maelplaine** [comment]
@chugginselifesciences Here is the list that I mentioned: https://docs.google.com/document/d/1r1xs-1aRoQamnwK4nLgfPWxiJs1L4AaRXlADL8p0aLg/edit

**Comment by thewilkybarkid** [comment]
@chugginselifesciences Do we have an image to go on the demo site?

**Comment by chugginselifesciences** [comment]
@thewilkybarkid Apologies I sent to David on slack a couple of weeks ago but should have added here too. This zip includes jpg and png at 1x and 2x, assuming we'll need larger images for retina displays etc. 

It's [this image from pexels](https://www.pexels.com/photo/scenic-view-of-mountain-during-evening-2085998/), and I've already added an overlay so should be dark enough for contrast with white text. Attribution isn't required, but you can see [more about the licence here](https://www.pexels.com/photo-license/) if you like.


[banner-stock-image.zip](https://github.com/libero/publisher/files/3376674/banner-stock-image.zip)


It's pretty boring to be honest and not relevant to the journal. I tried to put something together with the illustrations Nick had made for the product site, but it didn't really work with a dark overlay and the aspect ratio. I think instead we could create something using the new logo for more relevance and consistent branding?

**Comment by Maelplaine** [comment]
Thanks @chugginselifesciences this banner is fine for now. At least we have something for next week's press release. We can update the image later with a better one.

**Comment by davidcmoulton** [comment]
Initial PR https://github.com/libero/publisher/issues/138

**Comment by chugginselifesciences** [comment]
@discodavey same stock image without overlay

[banner-image-no-overlay.zip](https://github.com/libero/publisher/files/3385984/banner-image-no-overlay.zip)

**Comment by chugginselifesciences** [comment]
@discodavey webp formats 

[banner-webp.zip](https://github.com/libero/publisher/files/3391558/banner-webp.zip)
