### ISSUE TITLE
Add menu to header

### ISSUE THREAD

**Issue by thewilkybarkid** [libero/publisher#140]
Add menu to the header

<img width="1334" alt="Screenshot 2019-04-17 at 08 44 56" src="https://user-images.githubusercontent.com/1784740/56270111-4bfe8d80-60ed-11e9-8808-e001f8c3c48e.png">

## Tasks

- [x] Create menu pattern (https://github.com/libero/pattern-library/pull/129)
- [x] Add to header pattern (https://github.com/libero/pattern-library/pull/129)
- [x] Add to Browser (just a 'Home' item) (https://github.com/libero/browser/pull/105)

## Notes

- I'm not separating the template and styles.
- Menu items are customisable.

## Related

- Follows #139 (add header).

**Comment by thewilkybarkid** [comment]
@chugginselifesciences What should happen if there's too many to show in one line? (eg likely to happen on mobiles)

**Comment by chugginselifesciences** [comment]
@thewilkybarkid For the MVP and for IJM I think I'd mocked it up to check it fits on our smallest supported screens, but I'll double check.

For more flexibility in adding items in future, and for other journals we have a few options, but my assumption so far is it would overflow into a hamburger menu similar to what we have on eLife's 'current' journal. There's also the option to go to the two rows of menu again the same as eLife's header, if needed. But I don't have a solid, tested solution right now.

I'd assumed we're safe to get on with the MVP and address this later but if not the case Nick and I can look into a longer term solution.

**Comment by thewilkybarkid** [comment]
Ok, for now we can just let it be side-scrollable.

**Comment by chugginselifesciences** [comment]
This is it at 320px. As I understand it, we won't have login/profile or submit buttons. Should be room for search if it's going to be in the MVP.

![image](https://user-images.githubusercontent.com/41907215/56277594-8de30000-60fc-11e9-8480-c15a64b99349.png)

**Comment by thewilkybarkid** [comment]
Fine for those 3 items in English, but might cause problems for other languages/a 4th item. While that it was we'll be initially demoing, don't want to make such assumptions. Side-scrolling isn't a great experience, but it'll get round potentially broken layouts.

**Comment by chugginselifesciences** [comment]
Let's stick with the side scrolling for now. I've booked in a brainstorming session to look at longer term/more flexible, scalable solutions for later release(s).

**Comment by thewilkybarkid** [comment]
Done first pass at adding the menu at https://github.com/libero/pattern-library/pull/129, will probably need to talk it through with @chugginselifesciences in person (to confirm spacing, overflow behaviour etc).

**Comment by thewilkybarkid** [comment]
Confirmed in person that it's ok for now.
