### ISSUE TITLE
Add lead para

### ISSUE THREAD

**Issue by thewilkybarkid** [libero/publisher#141]
Line of text to appear under the content header on the homepage:

<img width="1182" alt="Screenshot 2019-04-17 at 08 57 46" src="https://user-images.githubusercontent.com/1784740/56270815-ef03d700-60ee-11e9-9aa3-8d367a05ae42.png">

## Tasks

- [ ] Add pattern
  - [ ] Has a better name
- [ ] Add to Browser
- [ ] Add to the unstable environment

## Notes

- I'm not separating the template and styles.
- I don't like the name 'lead para'. This was just the eLife pattern name.
- Assuming it's ok to _not_ allow inline HTML for now.
- Unlike eLife, assuming it's ok to just have 1 line of text.
