### ISSUE TITLE
Add table pattern

### ISSUE THREAD

**Issue by thewilkybarkid** [libero/publisher#147]
Add unstyled table pattern.

## Tasks

- [ ] Create table(s) pattern
  - [ ] Handles 1 or more tables
  - [ ] Can be used in the figure pattern
- [ ] Added to Browser
- [ ] Added to the unstable environment

## Notes

- JATS to support:
  ```xml
  <table-wrap>
    <table>[..]</table>
  </table-wrap>
  ```
- May be contained in a `<fig>`.
- `<table>` must only contain `<thead>`, `<tbody>` and `<tfoot>`.
- `<th>` and `<td>` may contain existing supported elements (eg `<i>`).

## Related

- Blocks #148 (add styling).
