### ISSUE TITLE
Add author details

### ISSUE THREAD

**Issue by thewilkybarkid** [libero/publisher#149]
Add (possibly unstyled) author details section to articles, to contain author names and their institutions.

<img width="698" alt="Screenshot 2019-05-06 at 16 13 27" src="https://user-images.githubusercontent.com/1784740/57235047-eaf61580-7019-11e9-8cbc-690ae6a93edf.png">

## Tasks

- [ ] Decide on approach
- [ ] Pattern work (if any) done
- [ ] Add to Browser
  - [ ] Contains author names
  - [ ] Contains institution names
- [ ] Style issue created (if needed)

## Notes

- Unclear whether this requires a new pattern or can reuse the existing Section pattern.
- JATS support described in #145.

## Related

- #145 adds author and institution names to the content header.
