### ISSUE TITLE
Dummy static pages

### ISSUE THREAD

**Issue by giorgiosironi** [libero/publisher#15]
## Problem / Motivation
 
- WHO wants this? The journal stakeholder
- WHEN and WHERE do they want it? On the journal, accessible through navigation
- WHAT do they want? An example of page with static content
- WHY do they want this? To help them imagine the complete look&feel, to easily add slowly changing content

## Proposed solution

- Set of 0..N static pages configurable by a developer at deployment time
- Allow configuration of: URL, placement of (possibly multiple) navigations links in menu or navigation bars, text of those links
- Allow configuration of: title, impact statement, content (paragraphs, subheadings, links)

## Tasks

- [ ] Some kind of configuration deployed with the journal service
- [ ] Server-side controllers to generate the page
- [ ] Add link(s) to page(s)
- [ ] `About page` built with these components

## Clarification needed and assumptions

- Only configurable by a developer deploying the journal app for MVP, IJM, some other small journal
- No shared configuration between different journals, each has its own
- Styling of links is left to the default for each "navigation place", no special treatment

## Technical notes
...

## User interface / Wireframes

![about](https://user-images.githubusercontent.com/39725642/54270377-37bbf380-4577-11e9-8e04-1723abcfccbd.jpg)

**Comment by thewilkybarkid** [comment]
Agreed that for MVP the global navigation will have one item ('About', by default), there there is a set of pages inside that (so no tree structure).

**Comment by giorgiosironi** [comment]
Outdated, requirements have changed and now requires Markdown solution discovery.
