### ISSUE TITLE
Add references

### ISSUE THREAD

**Issue by thewilkybarkid** [libero/publisher#194]
Add basic reference list.

## Tasks

- [x] Create reference template (https://github.com/libero/pattern-library/pull/120)
- [x] Create reference list template (https://github.com/libero/pattern-library/pull/120)
- [x] Add JATS support (https://github.com/libero/jats-support/pull/15)
- [x] Add to Browser (https://github.com/libero/browser/pull/95)
- [x] Add to the unstable environment (https://github.com/libero/sample-configuration/pull/75)

## Notes

-  JATS to support:
    ```xml
    <article>
      <back>
        <ref-list>
          <ref>
            <element-citation>
              <article-title>[...]</article-title>
              <source>[...]</source>
              <person-group person-group-type="author">
                <name>
                  <surname/>
                  <given-names/>
                  <prefix/>
                  <suffix/>
                </name>
                [...]
              </person-group>
              <pub-id pub-id-type="doi">[...]</pub-id>
            </element-citation>
          </ref>
          [...]
        </ref-list>
      </back>
    </article>
    ```
    Only `<article-title>` is required.

## Related tasks

- Blocks #195 (add styling).
