### ISSUE TITLE
Style references

### ISSUE THREAD

**Issue by thewilkybarkid** [libero/publisher#195]
<img width="642" alt="Screenshot 2019-07-01 at 11 58 56" src="https://user-images.githubusercontent.com/1784740/60431402-a5a82b80-9bf7-11e9-829d-81cf2ff32b6e.png">

## Tasks

- [x] Style references (https://github.com/libero/pattern-library/pull/123)
- [x] Style reference list (https://github.com/libero/pattern-library/pull/123)
- [x] Browser updated (https://github.com/libero/browser/pull/95)

## Notes

- Assuming the number is generated content.

## Related tasks

- Blocked by #194 (add template).
