### ISSUE TITLE
Add elife demo content to the unstable environment

### ISSUE THREAD

**Issue by GiancarloFusiello** [libero/publisher#197]
A continuation of https://github.com/libero/libero/issues/170 except only concerning eLife content.

**Task**
Ensure the following articles can be successfully consumed by the `jats-ingester` and sent to the `scholarly-articles` service:
- [x] Greek characters: https://elifesciences.org/articles/41540
- [x] Subscripts: https://elifesciences.org/articles/46630
- [x] Greek and subscript: https://elifesciences.org/articles/44760
- [x] Superscripts: https://elifesciences.org/articles/43229
- [x] Superscripts: https://elifesciences.org/articles/40092
- [ ] Original test article: https://elifesciences.org/articles/09560
- [x] test convert tiff images: https://elifesciences.org/articles/36842

**Comment by GiancarloFusiello** [comment]
@gmaciocci Links to the uploaded versions of these articles:

- https://elifesciences.org/articles/41540
- https://unstable.libero.pub/articles/41540
&nbsp;

- https://elifesciences.org/articles/46630
- https://unstable.libero.pub/articles/46630
&nbsp;

- https://elifesciences.org/articles/44760
-  https://unstable.libero.pub/articles/44760
&nbsp;

- https://elifesciences.org/articles/43229
-  https://unstable.libero.pub/articles/43229
&nbsp;

- https://elifesciences.org/articles/40092
-  https://unstable.libero.pub/articles/40092
&nbsp;

- https://elifesciences.org/articles/36842
-  https://unstable.libero.pub/articles/36842


https://elifesciences.org/articles/09560 is currently not working due to parsing a doi reference incorrectly.

**Comment by FAtherden-eLife** [comment]
@gmaciocci 

Links to uploaded versions of these articles:
- https://elifesciences.org/articles/46187 
- https://unstable.libero.pub/articles/46187 

- https://elifesciences.org/articles/46962
- https://unstable.libero.pub/articles/46962

- https://elifesciences.org/articles/43173
- https://unstable.libero.pub/articles/43173

- https://elifesciences.org/articles/47085
- https://unstable.libero.pub/articles/47085

**Comment by GiancarloFusiello** [comment]
Content has been added to the unstable environment. Will suggest a new task be created for a final list of content to be added to the demo environment. The task of adding content has now been handed over to the publishing team. Closing.
