### ISSUE TITLE
Add Hindawi demo content to the unstable environment

### ISSUE THREAD

**Issue by GiancarloFusiello** [libero/publisher#198]
A continuation of https://github.com/libero/libero/issues/170 except only concerning Hindawi content.

**Task**
Ensure the following articles can be successfully consumed by the `jats-ingester` and sent to the `scholarly-articles` service:
- [ ] [BN_3683548_Final_1](https://github.com/libero/libero/files/3331160/BN_3683548_Final_1.zip)
- [ ] [CRIS_7292974_Final_5](https://github.com/libero/libero/files/3331161/CRIS_7292974_Final_5.zip)
- [ ] [JCNC_6826984_Final_1](https://github.com/libero/libero/files/3331162/JCNC_6826984_Final_1.zip)

**Comment by FAtherden-eLife** [comment]
@gmaciocci three Hindawi articles added:
- https://unstable.libero.pub/articles/3914828
- https://unstable.libero.pub/articles/8093192 (Content too graphic??)
- https://unstable.libero.pub/articles/7292974

**Comment by GiancarloFusiello** [comment]
Content has been added to the unstable environment. Will suggest a new task be created for a final list of content to be added to the demo environment. The task of adding content has now been handed over to the publishing team. Closing.
