### ISSUE TITLE
Add IJM demo content to the unstable environment

### ISSUE THREAD

**Issue by GiancarloFusiello** [libero/publisher#199]
A continuation of https://github.com/libero/libero/issues/170 except only concerning IJM content.

**Task**
Ensure the following articles can be successfully consumed by the `jats-ingester` and sent to the `scholarly-articles` service:
- [ ] greek characters, maths in tables: https://demo--ijm.elifesciences.org/articles/00035
- [ ] greek characters, and `<sup>`: https://demo--ijm.elifesciences.org/articles/00173
- [ ] `<sub>`, maths: https://demo--ijm.elifesciences.org/articles/00190

**Comment by Maelplaine** [comment]
[ijm-00173-vor-r2.zip](https://github.com/libero/libero/files/3355336/ijm-00173-vor-r2.zip)

@GiancarloFusiello Here is the zip for the second article (00173). It's fine if we just get this on in for the 10th of July

**Comment by FAtherden-eLife** [comment]
@gmaciocci 

Links to these IJM articles:
- https://demo--ijm.elifesciences.org/articles/00169
- https://unstable.libero.pub/articles/00169

- https://demo--ijm.elifesciences.org/articles/00086
- https://unstable.libero.pub/articles/00086

- https://demo--ijm.elifesciences.org/articles/00040
- https://unstable.libero.pub/articles/00040

**Comment by GiancarloFusiello** [comment]
Content has been added to the unstable environment. Will suggest a new task be created for a final list of content to be added to the demo environment. The task of adding content has now been handed over to the publishing team. Closing.
