### ISSUE TITLE
Update the Libero logo

### ISSUE THREAD

**Issue by BlueReZZ** [libero/publisher#205]
## Problem / Motivation
 
The logo of Libero has changed and needs to be updated on the demo journal so that it is consistent with the product website

@NickDuf can you attach logos in SVG and PNG here please?

## Tasks

- [x] Pattern Library updated (https://github.com/libero/pattern-library/pull/121)
  - [x] Site Header pattern
  - [x] Favicon
- [x] Browser updated (https://github.com/libero/browser/pull/97)
- [x] Slack
- [x] GitHub
- [x] `libero/publisher` (https://github.com/libero/publisher/pull/212)

**Comment by NickDuf** [comment]
Here is the logo it needs to be set to width: 122px, Height: 48px to render pixel perfect. Let me know when it is live and ready for review.

[libero-logo-48px.svg.zip](https://github.com/libero/publisher/files/3358822/libero-logo-48px.svg.zip)

**Comment by thewilkybarkid** [comment]
@NickDuf Could you provide the graphic part standalone too? (For the Favicon.)

It should also have a transparent background rather than white. An uncompressed version would be better too (we compress SVGs as part of the build process, so better to store the source).

**Comment by NickDuf** [comment]
Try this Chris. 116px x 48px should display pixel perfect

[revised-logo.zip](https://github.com/libero/publisher/files/3359329/revised-logo.zip)

**Comment by thewilkybarkid** [comment]
I've added things outside the demo site (eg GitHub), ok to do them now?

**Comment by BlueReZZ** [comment]
Yes, please change it everywhere it's seen. Let me know if I can help.

**Comment by thewilkybarkid** [comment]
@NickDuf https://github.com/libero/publisher should probably have the Libero Publisher logo (and be larger too)?

**Comment by NickDuf** [comment]
@thewilkybarkid no problem. I wanted to make sure that this one was working as anticipated before doing the rest. I will have the Publisher logo across shortly in a couple of sizes for you.

**Comment by NickDuf** [comment]
@thewilkybarkid here are two sizes for the publisher logo. 
[publisher-logos.zip](https://github.com/libero/publisher/files/3363268/publisher-logos.zip)

- 48 is 48px x 142px
- 32 file is 32px x 96px

**Comment by thewilkybarkid** [comment]
That would look pretty small on https://github.com/libero/publisher...

**Comment by NickDuf** [comment]
I see @thewilkybarkid. I didn't realise that it was for github. Here is the set for you to choose from. You can discard the ai files.

[libero-logo-publisher.zip](https://github.com/libero/publisher/files/3364414/libero-logo-publisher.zip)
