### ISSUE TITLE
Add Figure label pattern

### ISSUE THREAD

**Issue by Maelplaine** [libero/publisher#222]
- Figures need a label above their images

## Tasks

- [] Add to content header pattern
- [] Add to the article page on Browser
  - [] Supports multiple formats
  - [] Supports multiple sizes
- [] Add to the unstable environment (https://github.com/libero/sample-configuration/pull/78)

## Clarification needed and assumptions
- We are not going to support suppl figures for the MVP
> Yes, this is too specific to eLife's needs

## Technical notes
- We could use this technology 
- More notes or suggestions

## User interface / Wireframes

![image](https://user-images.githubusercontent.com/39725642/61620626-22637e00-ac69-11e9-8521-6ff14fecd116.png)

**Comment by FAtherden-eLife** [comment]
> We are not going to support suppl figures for the MVP
>> Yes, this is too specific to eLife's needs

However, one IJM article (`ijm-00039`) uses the JATS element `fig-group`, which has a label (as does its child `fig` elements):
```xml
<fig-group id="fig2">
    <label>Figure 2</label>
    <caption><title>Actual and Simulated Gross Migration Flows</title></caption>
    <fig id="fig2a" position="float">
        <label>(a)</label>
        <caption><title>k - based upon lagged transitions (1991-2000)</title></caption>
        <graphic xlink:href="ijm-00039-fig2a.tif" mimetype="image" mime-subtype="tiff"/>
    </fig>
    <fig id="fig2b" position="float">
        <label>(b)</label>
        <caption><title>k - based upon average transitions (1991-2000)</title></caption>
        <graphic xlink:href="ijm-00039-fig2b.tif" mimetype="image" mime-subtype="tiff"/>
    </fig>
    <fig id="fig2c" position="float">
        <label>(c)</label>
        <caption><title>k - based upon first transition in 1991 (1991-2000)</title></caption>
        <graphic xlink:href="ijm-00039-fig2c.tif" mimetype="image" mime-subtype="tiff"/>
    </fig>
</fig-group>
```

My understanding is that we're treating IJM as MVP, so this will need to accounted for too (whether that's here or in another ticket, I'm not sure).

**Comment by Melissa37** [comment]
@FAtherden-eLife we will need to ask Exeter to re-do this figure so parts a and b are retained in one figure and not split.

**Comment by Maelplaine** [comment]
Thanks for flagging this @FAtherden-eLife 
@discodavey Was is faster for us to develop? 
1) Rebuild what we have on eLife's website with the 2 navigation arrows to see the other figures
2) Or a quick workaround such as adding all the supplementary figures at the bottom of the article

**Comment by Melissa37** [comment]
Tracking Exeter resupply requirements here:
https://github.com/microsimulation/ijm-xml/projects/1

Ticket created for this issue:
https://github.com/microsimulation/ijm-xml/issues/139

Suggest we don't ask for resupplies from Exeter until you have completed review to prevent the possibility of asking for multiple resupplies.

They are aware we might ask for changes to their XML so if you think any tagging could be done better please don't hesitate to raise issues.

**Comment by Melissa37** [comment]
@Maelplaine please see my response. No work required by the eLife dev team.
I can triage what requires an Exeter resupply before asking the dev team to investigate :-) Will save energy on the eLife side.

**Comment by Maelplaine** [comment]
Ok I see. Thanks @Melissa37

**Comment by FAtherden-eLife** [comment]
Ah I see, thanks for clarifying @Melissa37!

**Comment by discodavey** [comment]
Draft Pull
https://github.com/libero/pattern-library/pull/133

**Comment by discodavey** [comment]
Have done the first bit of the pattern as in styling from eLife pattern and adding some of the twig. It's the first round of changes.

**Comment by FAtherden-eLife** [comment]
If we're including Hindawi content as MVP, then we need to account for the use of `fig-group`, which they use to group related figures together (not the same as eLife's 'supplementary figures'). I assume this pattern would be unaffected(?), but just adding an example here in the event this should be taken into account here:
```xml
<fig-group id="fig3">
<label>Figure 3</label>
<caption>
<p>Representative TUNEL staining slices for left ventricular myocardium. TUNEL: terminal dUTP nick end labeling. Apoptotic nuclei were stained brown. Apelin alleviated myocardial apoptosis induced by coronary artery ligation.</p></caption>
<fig id="fig3a">
<label>(a)</label>
<caption>
<p>Sham-operated</p></caption>
<graphic xlink:href="4823156.fig.003a"/></fig>
<fig id="fig3b">
<label>(b)</label>
<caption>
<p>Untreated HF</p></caption>
<graphic xlink:href="4823156.fig.003b"/></fig>
<fig id="fig3c">
<label>(c)</label>
<caption>
<p>Apelin-treated HF</p></caption>
<graphic xlink:href="4823156.fig.003c"/></fig></fig-group>
```
Screenshot of their PDF (as an indication of intended output):
<img width="930" alt="Screen Shot 2019-08-14 at 14 03 54" src="https://user-images.githubusercontent.com/43879983/63023228-89f19f80-be9c-11e9-9d0e-e3f5c031d41c.png">
