### ISSUE TITLE
Collapsible Figure captions

### ISSUE THREAD

**Issue by Maelplaine** [libero/publisher#223]
## Proposed solution
- The figure caption should be collapsible is the text is too long and java script is enabled

## Tasks

- [ ] Add to figure pattern
- [ ] Add to the article page on Browser
- [ ] Add to the unstable environment

## Clarification needed and assumptions

- At what point would we collapse the caption? (amount of characters / words)
> It looks like the threshold is 27 words or 200 characters on eLife. Let's do the same

## Technical notes
- We could use this technology 
- More notes or suggestions

**Comment by thewilkybarkid** [comment]
The implementation needs to be different to eLife's to avoid https://github.com/elifesciences/issues/issues/4269 (removing text from the DOM orphans Hypothesis annotations).
