### ISSUE TITLE
Display DOI on article page

### ISSUE THREAD

**Issue by Maelplaine** [libero/publisher#227]
## Problem / Motivation
 
- WHO wants this?
- WHEN and WHERE a- Figures need a label above their images

## Tasks

- [ ] Add to figure pattern
- [ ] Add to the article page on Browser
- [ ] Add to the unstable environment

## Clarification needed and assumptions
- Where is the data coming from?
> The DOI is in the XML of the article

## User interface / Wireframes

![image](https://user-images.githubusercontent.com/39725642/61620626-22637e00-ac69-11e9-8521-6ff14fecd116.png)

**Comment by Melissa37** [comment]
@Maelplaine this a good time to re-discuss the DOI display guidelines.
I know @gmaciocci did not want to display on the eLife site what Crossref request, but if this is being built for other publishers, who follow Crossref recommendations, then we should probably follow the "standard"/"requirement" when building Libero:

https://www.crossref.org/display-guidelines/

Display Crossref DOI as a full link
Crossref DOIs should always be displayed as a full URL link in the form

https://doi.org/10.xxxx/xxxxx

and should not be preceded by doi: or DOI:.

Example: https://doi.org/10.5468/ogs.2016.59.1.1

**Comment by Maelplaine** [comment]
Thanks @Melissa37 
@chugginselifesciences Would you mind updating the wireframes with their recommendations?

**Comment by chugginselifesciences** [comment]
@Maelplaine do you mean the InVision prototype?

**Comment by chugginselifesciences** [comment]
@Maelplaine Just to check I've understood, I'll update the InVision prototype with the below example. Assuming this is ok at least for eLife articles on demo.libero.pub? Or do we have a "Libero" specific DOI?

https://doi.org/10.7554/eLife.09560

**Comment by Maelplaine** [comment]
@chugginselifesciences We do not have a Libero specific DOI. I think it's better if the example DOI doesn't include the word eLife. Can you use this one instead? https://doi.org/10.5468/ogs.2016.59.1.1
That's the example used by Crossref

**Comment by chugginselifesciences** [comment]
@Maelplaine - I've updated the prototype - https://invis.io/87QKCKGYKJD#/347378983_IJPI-Home

Updated screen exports
[libero-demonstration-journal.zip](https://github.com/libero/publisher/files/3430941/libero-demonstration-journal.zip)

**Comment by Maelplaine** [comment]
Thanks @chugginselifesciences 
@discodavey I've updated the screenshot

**Comment by discodavey** [comment]
Chris and Nick have agreed with the padding top and bottom on this which is 12px. Total of height comes to 48 which is what Chris has on the design.

**Comment by discodavey** [comment]
https://github.com/libero/pattern-library/pull/131

**Comment by davidcmoulton** [comment]
@discodavey I've pushed some more [commits](https://github.com/libero/pattern-library/pull/131/commits) while you were off. Please take a moment to look at them and understand the changes that I've made, and why (you can ignore the one that just merges master into the the feature branch). Outstanding is updating the reference doi to use the doi mixin you've created, once you've done this it'll be ready for re-review by @thewilkybarkid so please let him know when it's it is.

**Comment by discodavey** [comment]
PR - https://github.com/libero/pattern-library/pull/131
