### ISSUE TITLE
Define JATS heuristic for mandatory information

### ISSUE THREAD

**Issue by Maelplaine** [libero/publisher#229]
## Problem / Motivation
- WHO For the tech team
- WHAT Logic to determine key information from various JATS files
- WHY So that mandatory information can always be found

## Tasks
- [x] Investigate article ID and title variants
- [x] Determine detailed logic for finding information
- [ ] Determine where this logic should be held/implemented

## Clarification needed and assumptions
- Assumption: article ID and title are the only mandatory pieces of information
> @GiancarloFusiello and @thewilkybarkid Is that correct

**Comment by FAtherden-eLife** [comment]
## IDs
Content should be found as children of the following element `article/front/article-meta`
- IJM, Hindawi, and eLife use `article-id[@pub-id-type='publisher-id']` 
- bioRxiv don't use `article-id`. Looks like `elocation-id` is most appropriate equivalent, although we should question why they don't use it.
- 1 (and only) example article from SciELO doesn't have _any_ equivalent, and no doi. This is problematic.

(examples of other `@pub-id-type` variants publishers use from PMC include `art-access-id`, `manuscript`, `other`, `pii`, `publisher-manuscript`).

Examples of `article-id` elements which _should_ be ignored in this context:
- `article-id[@pub-id-type="pmid"]`
- `article-id[@pub-id-type="pmc"]`
- `article-id[@pub-id-type="doi"]`

**Opinion**: Libero should expect `article-id[@pub-id-type="publisher-id"]`. Where possible we should ask that publishers use this (SciELO for example). But there should be internal logic to determine the id when this element isn't present.

Logic for determining ID should be:
- if `article-id[@pub-id-type="publisher-id"]` then `article-id[@pub-id-type="publisher-id"]`
(preferred tagging)
- else if `article-id[not(@pub-id-type='pmid') and not(@pub-id-type='pmc') and not(@pub-id-type='doi')]` then that `article-id`
(article-id which isn't one of the other known types)
- else if `elocation-id` then `elocation-id`
(elocation-id used as article-id)
- else `article-id[@pub-id-type="doi"]`
(last resort)

Questions: 
- Where should this logic be held?
- Should the Schematron output a message to inform a publisher what is being used as the identifier?

**Comment by thewilkybarkid** [comment]
> * Assumption: article ID and title are the only mandatory pieces of information

'title' definitely is (we have to be able to display _something_!), unclear about 'id' (might be able to use a surrogate key instead).

**Comment by Melissa37** [comment]
>unclear about 'id' (might be able to use a surrogate key instead).

I don't think it would be unreasonable to expect an identifier for the article and for that to be a requirement for using Libero, especially given the options for what can be used.
If we make it clear the logic set out and if a publisher uses none of these they need to start if they want to use Libero. I worry about the system creating a new identifier that the publisher has not determined themselves as how would they then use it?

**Comment by thewilkybarkid** [comment]
> I worry about the system creating a new identifier that the publisher has not determined themselves as how would they then use it?

Surrogate keys are for internal use, so they (probably) wouldn't.

I'm not saying that we would do this either, just mindful of the fact that eLife once re-numbered a few articles.

**Comment by FAtherden-eLife** [comment]
## Title

- JATS publishing (blue) and authoring (orange) mandates the presence of `article/front/article-meta/title-group/article-title` in every article. 
- JATS archiving and interchange (green) doesn't mandate an article title. 

In the vast majority of cases, there will be an `article-title`, regardless of what colour JATS is being used. (I understand that Érudit, for example, have some articles in which `article-title` is not used.)

`article-title` should be considered as in the original language of the rest of the article. Any translated titles should be found in `article/front/article-meta/title-group/trans-title-group/trans-title`. Note that there may be numerous translated titles. 

`subtitle` may also be found in `title-group`. This will have to be dealt with for MVP (18 IJM articles have subtitles), but is beyond the scope of this ticket.

**Opinion**: Mandate that `article/front/article-meta/title-group/article-title` must be present in order for Libero publisher to ingest an article. If potential adopters approach us with exceptions, then we can explore this after MVP.

**Comment by Melissa37** [comment]
Sounds good, agree. 

Just curious as to what type of articles Érudit publishes that don't have article-title. Could we reach out and ask them? 

>Do we add an error message to the Schematron for this?
Do you mean a failure if there is no title?

**Comment by FAtherden-eLife** [comment]
> Just curious as to what type of articles Érudit publishes that don't have article-title. Could we reach out and ask them?

Book reviews - I think they use `product` instead. 

> > Do we add an error message to the Schematron for this?

> Do you mean a failure if there is no title?

Yes - presumably a question for @thewilkybarkid.

**Comment by thewilkybarkid** [comment]
> > Do you mean a failure if there is no title?
> 
> Yes - presumably a question for @thewilkybarkid.

It's the one `error` at the moment: https://github.com/libero/jats-support/blob/a30483627efe0383ca0d1162ec2a64ad245c0a3d/src/support.sch#L140-L146

**Comment by Melissa37** [comment]
>Book reviews - I think they use `product` instead.

IJM will switch to this model for their books reviews too though, if that's the best semantic way to model the JATS? IJM is full of product reviews...

**Comment by FAtherden-eLife** [comment]
> It's the one error at the moment: https://github.com/libero/jats-support/blob/a30483627efe0383ca0d1162ec2a64ad245c0a3d/src/support.sch#L140-L146

That specifies `title-group`. The following is currently valid:
```xml
<article>
    <front>
        <article-meta>
            <title-group>
                
            </title-group>
        </article-meta>
    </front>
    <body>
        
    </body>
</article>
```

[This pr](https://github.com/libero/jats-support/pull/20) includes a test mandating `article-title`.

**Comment by FAtherden-eLife** [comment]
> `<title-group>` requires an `<article-title>` in the JATS schema?

Yup (I meant valid against the JATS-support Schematron). Are we validating JATS content against whatever colour DTD is used? 

If not, then surely it would make sense to be specific in the Schematron?

**Comment by FAtherden-eLife** [comment]
> Book reviews - I think they use product instead.

> > IJM will switch to this model for their books reviews too though, if that's the best semantic way to model the JATS? IJM is full of product reviews...

@Melissa37 what do you mean by model? Including `product` in place of `article-meta`? Looks like currently `product` is included in `article-meta` as well as an `article-title` - I would say this is preferable capture.

**Comment by Melissa37** [comment]
>@Melissa37 what do you mean by model? Including product in place of article-meta? Looks like currently product is included in article-meta as well as an article-title - I would say this is preferable capture.

Thanks @FAtherden-eLife perfect. Sorry, I was being lazy and should have looked up the other conversations/xml samples.

**Comment by FAtherden-eLife** [comment]
No problem - thanks!

**Comment by thewilkybarkid** [comment]
> Are we validating JATS content against whatever colour DTD is used?
>
> If not, then surely it would make sense to be specific in the Schematron?

We'll definitely only support valid JATS, but _which_ JATS becomes the relevant question here!

**Comment by FAtherden-eLife** [comment]
> We'll definitely only support valid JATS, but _which_ JATS becomes the relevant question here!

Yup. I still think it would be preferable to be as prescriptive as possible with the Schematron (that `article-title`, as well as `title-group`, is needed) even if that's defined elsewhere, but up to you.

**Comment by FAtherden-eLife** [comment]
@GiancarloFusiello are you Ok to add the following logic into the jats-ingester?
- if `article-id[@pub-id-type="publisher-id"]` then `article-id[@pub-id-type="publisher-id"]`
(preferred tagging)
- else if `article-id[not(@pub-id-type='pmid') and not(@pub-id-type='pmc') and not(@pub-id-type='doi')]` then that `article-id`
(article-id which isn't one of the other known types)
- else if `elocation-id` then `elocation-id`
(elocation-id used as article-id)
- else if `article-id[@pub-id-type="doi"]` then `article-id[@pub-id-type="doi"]`
(last resort)
- else **fail**

**Comment by FAtherden-eLife** [comment]
@thewilkybarkid, the above logic could be relayed to a publisher via Schematron validation. Something [like this](https://github.com/libero/jats-support/pull/21) is a possibility. Do you think that could be useful?

**Comment by GiancarloFusiello** [comment]
@FAtherden-eLife yes I can add this but I think the role of the `jats-ingester` along with the rest of the Libero suite is being discussed at this point and so I'm hesitant to do any more work until the product/s have been more clearly defined. In principle, happy to add this whenever we're ready.

**Comment by FAtherden-eLife** [comment]
> @FAtherden-eLife yes I can add this but I think the role of the `jats-ingester` along with the rest of the Libero suite is being discussed at this point and so I'm hesitant to do any more work until the product/s have been more clearly defined. In principle, happy to add this whenever we're ready.

Makes sense - sounds good to me - thanks!

**Comment by BlueReZZ** [comment]
The role of `jats-ingester` is to cope with the general case for finding this mandatory fields so I think this is the right place to put it and there's no need to wait to consider how we're cope with the more specific case. I'm happy for it to go into `jats-ingester` now. @GiancarloFusiello I'd suggest creating a new issue for that and copying over the exact spec as @FAtherden-eLife has defined.

**Comment by GiancarloFusiello** [comment]
Creating ticket.
