### ISSUE TITLE
Create Categories service

### ISSUE THREAD

**Issue by GiancarloFusiello** [libero/publisher#230]
**Prerequisite**:
- [ ] [Move Python Flask XML errors and ping endpoint into separate repositories](https://github.com/libero/publisher/issues/233)

**Tasks**:
- [ ] Create a service with a dedicated database used to store categories.
- [ ] The service should provide a RESTful API for interacting with data using `application/xml` mime type.
- [ ]  Use the following schema for a single Category object:
```
Category {
  id: long int,
  name: string (required),
  slug: url safe string
}
``` 
- [ ] If not provided, the `slug` field should be generated from the `name` field
- [ ]  Use `/{id}` endpoint for all CRUD operations via REST API
- [ ]  Use `/` endpoint for listing categories

**Comment by giorgiosironi** [comment]
https://github.com/libero/publisher/issues/228#issuecomment-518562664 suggests using configuration rather than a database, which would remove `C`, `U` and `D` from the API and the database itself from the footprint of the service. Would also make multitenancy evolution simpler, as in migrating a configuration file rather than a schema.

**Comment by GiancarloFusiello** [comment]
> [#228 (comment)](https://github.com/libero/publisher/issues/228#issuecomment-518562664) suggests using configuration rather than a database, which would remove `C`, `U` and `D` from the API and the database itself from the footprint of the service. Would also make multitenancy evolution simpler, as in migrating a configuration file rather than a schema.

This would move the responsibility of maintaining these lists (creating, updating and deleting entries) to server side engineers. Also, would imply the need to re-deploy services to make such changes. I suspect users would want to be able to change entries themselves without having to create a ticket.

**Comment by giorgiosironi** [comment]
Explained in person: configuration files as a stepping stone towards a easy to evolve model for categories; as soon as there is a way for users (a generic term here) to maintain them a database and an API are needed along with a UI.

**Comment by giorgiosironi** [comment]
A inflection point for this service is whether it has responsibility of collecting the articles associated to a subject to answer the queries that build up the listing pages in the UI. In general I suspect this would likely create mutual dependencies between services and should be avoided.

**Comment by giorgiosironi** [comment]
To understand what API requests this service should answer, I would like to see designs for:
- the Libero Publisher equivalent of https://elifesciences.org/subjects if there is such a thing
- the Libero Publisher equivalent of the subjects box under `eLife works to improve research communication through ...` at https://elifesciences.org/ if there is such a thing
- the Libero Publisher (Dashboard?) equivalent of https://prod--journal-cms.elifesciences.org/admin/structure/taxonomy/manage/subjects/overview if there is such a thing

**Comment by giorgiosironi** [comment]
Strawman while we discover this: why shouldn't this be a [`content-store`](https://github.com/libero/content-store) with a certain XML or JSON (or any other format) defined for its items?

**Comment by giorgiosironi** [comment]
The intent of this ticket has been replaced by a differently named service. Can we close this in favor of those?

**Comment by giorgiosironi** [comment]
(can still reopen if needed)
