### ISSUE TITLE
Make scholarly content detail service ready for production use

### ISSUE THREAD

**Issue by GiancarloFusiello** [libero/publisher#238]
**Tasks**
- [ ] create production ready docker container image for deployment
- [ ] add healthcheck and/or smoke tests for production container (which ones?)
- [ ] push image
- [ ] deploy to `unstable` (whether it is still to `docker-compose` or Kubernetes)
- [ ] call APIs to populate data for categories in `unstable` and/or `demo`
