### ISSUE TITLE
jats-ingester integration with scholarly-content-detail

### ISSUE THREAD

**Issue by giorgiosironi** [libero/publisher#245]
## Tasks

- [x] get categories from the JATS using our Libero module in `jats-ingester`, [_Known idioms_ section](https://docs.google.com/document/d/1PmLD6NEiqpjKTnjW-n1Hho_G-znp5lW3ba8PGmOHnQE/edit?ts=5d7759c4#)
  - [x] currently suggested XPath: `article-categories/subj-group[not(@subj-group-type="heading")]/subject[1]`
- [x] a stub of `scholarly-content-detail` is used in development
- [x] GET /categories filtering by name (probably different calls for different categories)
- [x] `POST` or `PUT` on the category, autocreating it, if not already present.
- [x] mapping from categories stored in service to categories in the JATS XML
- [x] [PUT](https://github.com/libero/publisher/issues/243) with the categories ids
- [x] test with the test assets in `jats-ingester` (assuming they follow a supported format, otherwise exclude)

**Comment by giorgiosironi** [comment]
1. What are the precise XPaths referred to in `XML case ...`?

**Comment by giorgiosironi** [comment]
Answer to 1 is an XPath I have put in the description to the best of my knowledge.
Answer to 3 is purely textual match (string equality) so far.
Can a set be produced from the current test data in `demo.libero.pub` to start to answer 2? Pending @FAtherden-eLife confirmation once we have it.

**Comment by FAtherden-eLife** [comment]
1. Yes, XPath (in Clark notation) is `//*:article-categories/*:subj-group[not(@subj-group-type="heading")]/*:subject[1]`

3. Yes treating the content of `subject` as a string (ignoring any formatting tags such as `italic`)

Test data (answer to 2) follow shortly...

**Comment by giorgiosironi** [comment]
Added auto-creation of the category. We should be insert a removable step that creates the category if not already present; this creates possible problems downstream like:

- a typo propagating through the system and creating a different category that needs to be removed
- missing categories in environment in which they are not prepopulated
- possible future designs that have a mandatory property for a category (such as an image) breaking as it can't be provided

This is reasonsa

**Comment by giorgiosironi** [comment]
> Has a decision been made regarding the mapping of categories

My assumption is that it's an exact string match between:
- the service value
- the XML value with stripped tags
The complexity about lowercase/uppercase variations corner case is captured in https://github.com/libero/publisher/issues/242
For any other cases that arises, @FAtherden-eLife is our go-to person that can take decisions on the best way to handle them so you can ask directly.

**Comment by GiancarloFusiello** [comment]
Will close once the above have been merged.

**Comment by GiancarloFusiello** [comment]
I've purposely not merged https://github.com/libero/jats-ingester/pull/54 as this will add a task that will fail as the `scholarly-content-details` service has not been added to either staging or demo environments.

Also, given recent discussions, I'm not sure if we need ticket https://github.com/libero/publisher/issues/246 anymore.

Should this ticket and https://github.com/libero/publisher/issues/246 be closed?
