### ISSUE TITLE
Investigate using JSX templating for Publisher's UI patterns

### ISSUE THREAD

**Issue by davidcmoulton** [libero/publisher#250]
## Problem / Motivation

 
Using JSX would align the UI pattern templating language between Publisher and Reviewer.

Generated from https://github.com/libero/publisher/issues/248.

## Proposed solution

Find one or more nodejs-driven pattern libraries that can render JSX patterns and try it / them out. 

## Tasks

- [ ] identify pattern library candidate(s)
- [ ] assess likely viability
- [ ] try building patterns with each viable candidate
- [ ] evaluate

## Clarification needed and assumptions

- assumes possibility of switching the Publisher web app from PHP to nodejs.
