### ISSUE TITLE
Set up Storybook for HTML as Publisher's pattern library

### ISSUE THREAD

**Issue by davidcmoulton** [libero/publisher#255]
## Problem / Motivation
Moving from PHP to JavaScript for the Publisher web app.

## Context
[Discovery document - front end technology alignment](https://docs.google.com/document/d/1FkdvBjSb1BH1fhgujtppunvL_NX5U3xVuxv7L0fV010/edit#heading=h.oip2sudw7pju).

## Proposed solution
Use [Storybook](https://storybook.js.org/) for HTML as the pattern library to host the Publisher patterns.

**This is a trial** for the building of the next set of patterns. Such real world usage will help us decide on whether to proceed with Storybook as the new pattern library tool for Publisher.

## Tasks
- [x] set up Storybook for HTML (https://github.com/libero/storybook/pull/3)
- [x] install required add ons (in the first instance match Reviewer's Storybook add on feature set, modifying as required)
  - [x] Accessibility (https://github.com/libero/storybook/pull/8)
  - [x] Centered (https://github.com/libero/storybook/pull/7)
  - [x] Viewport (https://github.com/libero/storybook/pull/6)

## Clarification needed and assumptions

Observations relating to deciding whether this trial is successful will be made available in this ticket.

**Comment by thewilkybarkid** [comment]
Creating https://github.com/libero/storybook.

**Comment by thewilkybarkid** [comment]
(Trying out Makefile and Conventional Commits.)

**Comment by davidcmoulton** [comment]
Installation of Notes addon broken out into https://github.com/libero/publisher/issues/266.

**Comment by davidcmoulton** [comment]
Installation of Knobs plugin broken out into #267.
