### ISSUE TITLE
Add atoms to Storybook

### ISSUE THREAD

**Issue by discodavey** [libero/publisher#282]
Add atom patterns to Storybook

## Tasks

- [x] Add ```<sup>``` pattern
- [x] Add ```<sub>``` pattern
- [x] Add ```<time>``` pattern
- [x] Add ```<b>``` bold pattern
- [x] Add ```<strong>``` pattern

Adding these patterns to start of with as nearly complete but all patterns going forward will have their own ticket.

**Comment by discodavey** [comment]
PR's for this ticket

```<sup>```
https://github.com/libero/storybook/pull/29

```<sub>```
https://github.com/libero/storybook/pull/28

```<time>```
https://github.com/libero/storybook/pull/27

```<b>```
https://github.com/libero/storybook/pull/26

```<strong>```
https://github.com/libero/storybook/pull/25

**Comment by discodavey** [comment]
These have now all been approved and merged so will close the ticket.
