### ISSUE TITLE
Create Article Store

### ISSUE THREAD

**Issue by thewilkybarkid** [libero/publisher#289]
Create the Article Store API, with an empty Hydra endpoint.

## Tasks

- [x] Create project (https://github.com/libero/article-store/commit/df918be0912c2073d763b32f36d8e75dee3f6d08 https://github.com/libero/article-store/pull/1)
- [x] Create server (https://github.com/libero/article-store/pull/3)
  - [x] Create endpoint (https://github.com/libero/article-store/pull/10)
  - ~Has API documentation~ (#314)
  - [x] Handle errors
- [x] Linting (https://github.com/libero/article-store/pull/4)
- [x] Testing (https://github.com/libero/article-store/pull/6)
- ~View in [generic.hypermedia.app](https://github.com/hypermedia-app/generic.hypermedia.app)~ (https://github.com/libero/publisher/issues/315)

## Related

- Blocks #314 (add Hydra).
- Relates to #293 (API standard).
