### ISSUE TITLE
Allow creation of an article

### ISSUE THREAD

**Issue by thewilkybarkid** [libero/publisher#291]
Add an operation to add an article to the Article Store

## Tasks

- [x] Introduce repository to retrieve article listing (https://github.com/libero/article-store/pull/47)
- [x] Add create article operation (https://github.com/libero/article-store/pull/43)
  - [x] Accessible from collection (https://github.com/libero/article-store/pull/43)
  - [x] Validates that an ID is not already set (https://github.com/libero/article-store/pull/43)
  - [x] Validates there's at least one `schema:name` (https://github.com/libero/article-store/pull/88)
  - [x] Validates that it is a `schema:Article` (https://github.com/libero/article-store/pull/88)
  - [x] Stores the article in expanded JSON-LD (https://github.com/libero/article-store/pull/88)

## Related

- ~~Blocked by #290 (add article list).~~
- Relates to #292 (use a database).
