### ISSUE TITLE
Create a Kubernetes cluster

### ISSUE THREAD

**Issue by giorgiosironi** [libero/publisher#312]
Definition of Done:

- [x] ~[article-store](https://github.com/libero/article-store/)~ `nginx` is running on a Kubernetes cluster in the Libero AWS account. Manual deployment via `kubectl` is acceptable.

## Related

- `Kubernetes support` in the [Libero infrastructure roadmap](https://docs.google.com/document/d/1zJJdzKYRA_XHvH0jctqHUatl-kqjhAIfXuNRm8zoKBc/edit#).
- ~Depends on~ Now does not depend on https://github.com/elifesciences/issues/issues/5251
- Depends on https://github.com/libero/publisher/issues/349
- Not really depends on https://github.com/libero/publisher/issues/310 but helpful for validating everything works. We could run an `nginx` or similar container as a test instead.

## Tasks

- [x] Auto-download `libero/infrastructure` `terraform` binary to reuse correct version across `dev` and `ci` environments
- [x] Upgrade `libero/infrastructure` `terraform` to 0.12 using a `test` cluster
- [x] Apply to `unstable`
- [x] Apply to `demo`
- [x] ~Make EC2 setup optional through a variable to speed up development~ Create a separate environment using modules
- [x] Introduce the [EKS module](https://github.com/terraform-aws-modules/terraform-aws-eks)
- [x] ~Create VPC if necessary~ ~Use existing VPC~ Create VPC specific for EKS
- [x] Create 2 public subnets using the public routing table
- [x] [Tag subnets](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/examples/basic/main.tf)
- [x] Create workers security group (only one? what about the master one?)
- [x] Any other resource (roles for users?)
- [x] ~Install dependencies if needed (`kubectl`, `aws-iam-authenticator`)~ (they're not with the `master` version)
- [x] Add `kubernetes` provider if needed
- [x] Understand `mapAccounts`
- [x] Understand `mapUsers`
- [x] Understand `mapRoles`
- [x] Integrate `NodePort` Services
- [x] Extract `variables.tf` files and add `description`|`default` fields
- [x] Extract `outputs.tf` files and add `description` fields
- [x] Rename from `buzz` to `franklin`
- [x] Recreate with `TravisCI` credentials
- [x] Give permissions to `TravisCI` IAM user
- [x] Apply to `unstable` (null operation)
- [x] Apply to `demo` (null operation)
- [x] Documentation of some sort

**Comment by giorgiosironi** [comment]
https://github.com/terraform-aws-modules/terraform-aws-eks is promising so that we can avoid maintaining all the subnets, roles and similar resources.

**Comment by giorgiosironi** [comment]
SETI's log, stardate Q4 2019. Have been working on making parts of `infrastructure` optional through the use of variables, but the lack of an `if` construct makes everything relying on the `count` attribute varying between 0 and 1 which add lots of verbosity on dependent resources and outputs.

A better way to go at it should be to define [internal modules](https://www.hashicorp.com/resources/evolving-infrastructure-terraform-opencredo) that are composed at the top level by environments. This would also completely decouple whether an environment like `unstable` contains Publisher or Reviewer resources, or both. In any case, more digging before settling on a solution is helpful. Might drop the "optional" part for now or partially implement it with these ugly `count`s.

**Comment by giorgiosironi** [comment]
https://github.com/libero/infrastructure/pull/41 shows this approach; but since the intent is to show service providers how to run a Libero product, those hacks should be dropped in favor of a modules-based approach (or anything better). Also opens up the possibility for those modules to be rewritten as reusable modules published on the [Terraform registry](https://registry.terraform.io/).

**Comment by giorgiosironi** [comment]
https://github.com/libero/infrastructure/pull/42 ready for review, showing a plan output in the build. All checklist items tested before destroying the cluster.
