### ISSUE TITLE
Add Hydra UI to the Article Store

### ISSUE THREAD

**Issue by thewilkybarkid** [libero/publisher#315]
Add [generic.hypermedia.app](https://github.com/hypermedia-app/generic.hypermedia.app) to the Article Store's Docker setup, which creates a user interface for the API (so you don't have to use cURL or similar).

## Tasks

- [x] Create Docker image (https://github.com/hypermedia-app/generic.hypermedia.app/issues/41)
- [x] Enable CORS (https://github.com/libero/article-store/pull/11)
- [x] Add to Article Store (https://github.com/libero/article-store/pull/21)

## Related

- Blocked by #314 (add Hydra).
- Relates to https://github.com/hypermedia-app/generic.hypermedia.app/issues/42 (add entrypoint as config).
