### ISSUE TITLE
Implement page and content grid for article page in Storybook

### ISSUE THREAD

**Issue by davidcmoulton** [libero/publisher#336]
Definition of Done:

- [x] [page grid template](https://github.com/libero/pattern-library/tree/master/source/patterns/03-templates/page-grid) from Pattern Lab implemented in Storybook
- [x] [content grid template](https://github.com/libero/pattern-library/tree/master/source/patterns/03-templates/content-grid) from Pattern Lab implemented in Storybook
- [x] [corresponding grid styles](https://github.com/libero/pattern-library/blob/master/source/sass/base/_grid.scss) from Pattern Lab implemented in Storybook
- [x] Add appropriate documentation to the README.

## Related

Some refactoring will be necessary to bring the styling to use sass modules.

Conceptually related to #329.

- Assumption: the [listing grid](https://github.com/libero/pattern-library/tree/master/source/patterns/03-templates/listing-grid) is out of scope as the deliverable driving this ticket [specifies the article title](https://trello.com/c/410FhHvd/97-technology-adaptation-article-title).

## Tasks

- [x] page-grid
- [x] content-grid
- [x] styles
- [x] README update

**Comment by davidcmoulton** [comment]
PR: https://github.com/libero/storybook/pull/39
