### ISSUE TITLE
Multitenancy discovery: use cases generation

### ISSUE THREAD

**Issue by giorgiosironi** [libero/publisher#338]
[Discovery document](https://docs.google.com/document/d/1FPRUBfZo0YzktUevGu1jcmakdSKUq3smnw-zoCy3xdQ/edit?ts=5d6d3a68#heading=h.tpcwpla9877m)

Definition of Done:

- [ ] List of personas in the Scenarios section is deemed complete by @Maelplaine 
- [ ] Unsupported personas are strikethrough
- [ ] List of scenarios for each persona is deemed complete
- [ ] Unsupported scenarios are strikethrough

## Related

- Split from #263

## Tasks

TBD
