### ISSUE TITLE
Port article-store build to Github Actions

### ISSUE THREAD

**Issue by giorgiosironi** [libero/publisher#340]
Github Actions had a small trial in https://github.com/libero/community/pull/28. This is a test on an actual project containing TypeScript code and Docker builds.

Definition of Done:

- [x] The actions in https://github.com/libero/article-store/blob/master/.travis.yml should be executed within Github Actions

## Tasks

Tasks assume an happy path, but problems may arise.

- [x] Add Github Actions build for one target of `make build`
- [x] Build both `prod` and `dev`
- [x] Run smoke tests
- [x] Run `make lint`
- [x] Run `make test`
- [x] Port anything else that has been added after this ticket was created
- [x] Integrate with forks
- [x] Rename Travis CI specific scripts
- [x] Remove Travis CI build

**Comment by giorgiosironi** [comment]
Interestingly:
> Pull request events for forked repositories

> Note: Workflows do not run on private base repositories when you open a pull request from a forked repository.

> When you create a pull request from a forked repository to the base repository, GitHub sends the pull_request event to the base repository and no pull request events occur on the forked repository.

> Workflows don't run on forked repositories by default. You must enable GitHub Actions in the Actions tab of the forked repository.

**Comment by giorgiosironi** [comment]
More on security problems on forks with possible updates from Github: https://github.community/t5/GitHub-Actions/Github-Workflow-not-running-from-pull-request-from-forked/m-p/33547/highlight/true#M1555

Will work on the origin repository for demonstrating.

**Comment by giorgiosironi** [comment]
https://github.community/t5/GitHub-Actions/Run-a-GitHub-action-on-pull-request-for-PR-opened-from-a-forked/m-p/31147#M690:
> A workflow that specifies a pull_request as the event will always run in the repository that contains that pull_request.  So when I raise a pull_request to the upstream repo from a fork of that repo the workflow run will be in that upstream repo.  

The "enabling" was probably referring to the Beta period, in which you had to specifically enable this tab?

> During the beta you may or may not have GitHub Actions enabled in your user account or organization.  If you don't have GitHub Actions enabled forking a repo that has actions workflows into your account will not cause any runs to occur.

**Comment by giorgiosironi** [comment]
Like in Travis CI, [secrets are not available in forks](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/creating-and-using-encrypted-secrets#using-encrypted-secrets-in-a-workflow).
