### ISSUE TITLE
Adopt RDF/JS in the Article Store

### ISSUE THREAD

**Issue by thewilkybarkid** [libero/publisher#346]
JSON-LD is proving hard to use in code, we should try and use the [RDF JavaScript interfaces and libraries](https://rdf.js.org/).

## Definition of Done

- [ ] RDF/JS interfaces and library/ies are used instead of `jsonld`.

## Related

- Impacts https://github.com/libero/publisher/issues/291 (create article operation) and https://github.com/libero/publisher/issues/292 (add database).
- References https://github.com/libero/publisher/issues/292#issuecomment-557632503.

## Tasks

- [ ] Decide on approach
  - [ ] Consider how to combine 'static'  statements (eg 'this is an entrypoint') and dynamic (eg 'you have access to this operation')
  - [ ] Consider persistence
- [ ] Update code (https://github.com/libero/article-store/pull/64)

**Comment by thewilkybarkid** [comment]
Possible route is to create an RDF middleware that adds a `dataset` property to the response to contain a  [`DatasetCore`](https://rdf.js.org/dataset-spec/#datasetcore-interface). The handler could then add statements, either hard-coded (eg entrypoint) or sourced from a persistence layer (eg articles themselves), or both, as needed. On the way out it then serializes the dataset to the response body (still JSON-LD for now, but adds the potential for content negotiation).

**Comment by giorgiosironi** [comment]
Triage intended?

**Comment by thewilkybarkid** [comment]
Yeah, worth some feedback. (But I'm keen to introduce this now.)

**Comment by giorgiosironi** [comment]
Read through the specifications and have some more understanding of this, as an in-memory object model that can be rendered in a presentation layer to JSON-LD or something else.

**Comment by thewilkybarkid** [comment]
Going to close this for now. Doesn't seem like the full `Dataset` interface is usable ('experimental', _no_ implementations, unclear etc; refs https://gitter.im/rdfjs/public?at=5dee1b3905eec2433dfecade).

Streams seem to have good support, but is quite involved. Will probably have to formally timebox investigation into it.
