### ISSUE TITLE
Allow configurable dir and lang attributes on Storybook's <html>

### ISSUE THREAD

**Issue by davidcmoulton** [libero/publisher#347]
Definition of Done:

- [x] A Storybook page can be loaded with a configured value for the `<html>` `dir` attribute.
- [x] `dir` can be configured per story
- [x] A Storybook page can be loaded with a configured value for the `<html>` `lang` attribute.
- [x] `lang` can be configured per story
- [x] Merge in https://github.com/libero/storybook/pull/41

## Related
- Blocks https://github.com/libero/storybook/pull/31/
- Hinders other pattern work where desired presentation can't be fully demonstrated with respect to right to left reading direction.

## Tasks
- [x] Investigate https://storybook.js.org/docs/configurations/add-custom-head-tags/ and jump off from there.

**Comment by davidcmoulton** [comment]
PR: https://github.com/libero/storybook/pull/41
