### ISSUE TITLE
Auto-approve Dependabot upgrades

### ISSUE THREAD

**Issue by giorgiosironi** [libero/publisher#348]
Definition of Done:

Dependabot-originating pull requests should be auto approved so that they can be merged.

## Related

- https://github.com/dependabot/feedback/issues/86#issuecomment-523849759 has the state-of-the-art solution of using a [Github action](https://github.com/hmarr/auto-approve-action)`
- Requires a Github user to be created for maintenance
- Related to https://github.com/libero/publisher/issues/340

## Tasks

- [ ] Create Github user
- [ ] Give permissions for repositories
- [ ] Generate token with correct scope
- [ ] Store token in Github Actions 
- [ ] Add Github Action to repository with filter for Dependabot
