### ISSUE TITLE
Use Dockerised Hydra Analyser

### ISSUE THREAD

**Issue by thewilkybarkid** [libero/publisher#350]
Following https://github.com/libero/article-store/pull/33#discussion_r348490689, the Hydra Analyser has been Dockerised: https://hub.docker.com/r/hydrofoil/hydra-analyser. We should use it, rather than as an NPM dependency.

Definition of Done:

- [x] The `hydrofoil/hydra-analyser` container is used to run the Hydra analysis 

## Related

- Related to #351 (add Hypertest).

## Tasks

- [x] Switch to Docker image (https://github.com/libero/article-store/pull/102)
- [x] Remove NPM dependency (https://github.com/libero/article-store/pull/102)

**Comment by thewilkybarkid** [comment]
Wonder if we should replace [the script](https://github.com/libero/article-store/blob/master/.travis/analyse.sh) with Make?

**Comment by giorgiosironi** [comment]
Is the `trap` still necessary? Not sure how to cover that part to print logs.
