### ISSUE TITLE
Add Hypertest to the Article Store's CI

### ISSUE THREAD

**Issue by thewilkybarkid** [libero/publisher#351]
We should add [Hypertest](https://testing.hypermedia.app/dsl/) scenarios, which allows functional testing of the Hydra API.

It is now available as a container ([`hydrofoil/hypertest`](https://hub.docker.com/r/hydrofoil/hypertest)).

Definition of Done:

- [x] Hypertest scenarios are written for the API
- [x] Hypertest is run as part of CI

## Related

- Related to #335 (add Hydra Analyser), and #350 (use Dockerised Hydra Analyser).

## Tasks

- [x] Write article scenario (https://github.com/libero/article-store/pull/104)
- [x] Add script to run Hypertest (https://github.com/libero/article-store/pull/104)
- [x] Add to CI (https://github.com/libero/article-store/pull/104)
- [x] Make sure response bodies can be empty (https://github.com/libero/article-store/pull/111)
- [x] Use `201 Created` rather than `204 No Content` (https://github.com/libero/article-store/pull/112)

**Comment by giorgiosironi** [comment]
Weird tag `_0.2.0` but good to pin versions.

**Comment by giorgiosironi** [comment]
Just to confirm my understanding, this is a test runner and hence a job that terminates rather than a long-running service.
