### ISSUE TITLE
Provide Helm on Kubernetes clusters

### ISSUE THREAD

**Issue by giorgiosironi** [libero/publisher#359]
Definition of Done:

- [x] some sample Helm chart can be used to create a release and then destroy it on the `frankilin` environment

## Related

- Depends on https://github.com/libero/publisher/issues/312

## Tasks

- [x] Decide between Helm 2 and 3
- [x] Add installation of Helm to infrastructure as code if necessary (https://github.com/libero/infrastructure/pull/45)
- [x] Enable more people to issue Helm commands for redundancy (https://github.com/libero/infrastructure/pull/46)
- [x] Deploy some sample charts
- [x] Documentation of process (https://github.com/libero/infrastructure/pull/45)

**Comment by giorgiosironi** [comment]
Distilling the [upgrade FAQs](https://helm.sh/docs/faq/#changes-since-helm-2):

- there's no Tiller anymore and that simplifies security as you only need to care about the end user's permission
- out-of-band changes are merged and retained, or superseded by chart changes
- charts may eventually end up in registries shared with Docker images
- `Chart.yaml` now managed chart dependencies as well, and has `apiVersion: v2`

**Comment by giorgiosironi** [comment]
The Terraform provider is [not ready for Helm 3](https://github.com/terraform-providers/terraform-provider-helm/issues/299) though. Might have to run some `helm` commands manually or just not do this through Terraform is no `helm init` is required.

**Comment by giorgiosironi** [comment]
`helm init` is not a thing anymore, you can just download Helm 3 like for Terraform and add the repos or install packages. Still relies on `kubectl` authentication.

**Comment by giorgiosironi** [comment]
Task has become installing `helm` in `infrastructure`, currently for testing the whole process as it doesn't install anything yet. Plus, provide documentation so that anyone with `kubectl` access also has `helm` access.

**Comment by giorgiosironi** [comment]
Tested installation with
```
./helm install --generate-name stable/postgresql
./helm status postgresql-1578394613
./helm uninstall postgresql-1578394613
```
