### ISSUE TITLE
Create Helm chart for in-memory article-store

### ISSUE THREAD

**Issue by giorgiosironi** [libero/publisher#360]
Definition of Done:

- [x] `master` (or pinned version) of article-store should be able to run on a Kubernetes cluster

## Related

-  Split from https://github.com/libero/publisher/issues/358

## Tasks

- [x] Set up [repository](https://github.com/libero/publisher-chart/pull/1)
- [x] [`README`](https://github.com/libero/publisher-chart/pull/3)
- [x] `LICENSE`
- [x] [`Deployment`](https://github.com/libero/publisher-chart/pull/2)
- [x] minimal [`Service`](https://github.com/libero/publisher-chart/pull/4) (only one supported kind, likely `NodePort`)
- [x] `templates/tests` should contain a [test `Job`](https://github.com/libero/publisher-chart/pull/6)
- [x] introduce a [namespace](https://github.com/libero/publisher-chart/pull/5)
- [x] `readiness` and `liveness` probes
- [x] ~`resources` (if necessary)~
- [ ] Github Actions [build](https://github.com/libero/publisher-chart/pull/7) (to add [linting](https://github.com/libero/publisher-chart/pull/8))

**Comment by giorgiosironi** [comment]
Options for the scope of the repository:

1. all possible Libero charts (monorepo; even in Github Actions the CI will not play well with this)
2. `article-store` chart (but is it useful on its own? No use case for deploying independently at the moment)
3. Publisher vanilla version chart (can always add different flavors separately; similar to [`libero-reviewer` chart used in eLife](https://github.com/elifesciences/libero-reviewer-formula/); reasonable amount of repositories)

Going for 3.

**Comment by giorgiosironi** [comment]
@BlueReZZ taking into account the [proposed scope of this Infrastructure as Code effort](https://github.com/libero/community/pull/33), should we support deploying inside a [Kubernetes namespace](https://kubernetes.io/docs/concepts/overview/working-with-objects/namespaces/#when-to-use-multiple-namespaces)? That would provide:

- isolation of secrets (from other namespaces)
- quota for resources such as CPU and memory quotas

Cost is low, but that also means it's easier to add to the fork of this chart.

**Comment by BlueReZZ** [comment]
> Cost is low, but that also means it's easier to add to the fork of this chart.

This seems like a good justification for, and after a discussion IRL, it seems that namespaces might be expected as a sign of good practice/quality so would improve the perception of what we offer.

Worth adding IMO.
