### ISSUE TITLE
Add DNS entries to Libero deployments

### ISSUE THREAD

**Issue by giorgiosironi** [libero/publisher#363]
[ExternalDNS](https://github.com/helm/charts/tree/master/stable/external-dns) is a Kubernetes add-on that synchronizes annotations on Services with cloud provider DNS servers such as AWS Route 53.

Definition of Done: ExternalDNS is installed on Kubernetes clusters so that a Libero product can ask for stable DNS entries to be introduced for access to arbitrary microservices that should be exposed to the public Internet.

## Related

- Followed by https://github.com/libero/publisher/issues/376 (block public access to nodes behind a load balancer)

## Tasks

- [x] Turn the article store service resource into a load balancer
- [x] Add DNS annotation
- [x] Add IAM policy and attachment via Terraform
- [x] Install ExternalDNS via Terraform Helm provider
- [x] Update notes to cater for both custom and generic DNS
