### ISSUE TITLE
Support managed databases

### ISSUE THREAD

**Issue by giorgiosironi** [libero/publisher#366]
AWS and other cloud provider offer [managed databases](https://aws.amazon.com/products/databases/?nc2=h_ql_prod_db) that are easier to operate than running your own containers. These can optionally be integrated into an Helm chart that does not create them, but can configure the related microservices to use them.

Definition of Done:

- [x] `publisher--test-rds` uses an RDS Postgres database

## Tasks

- [x] Postgres is made optional in the Publisher Chart
- [x] Decide how to create an RDS instance
  - [x] Create the RDS instance
- [x] Explore networking
- [x] Explore RDS set up (eg use a new user)
- [x] Create `publisher--test-rds` release
- [x] Attach RDS to the release
- [x] Create a new Terraform module

**Comment by giorgiosironi** [comment]
In an uncertain future, there would be the possibility to manage RDS instances from Kubernetes resources in the same way as `Service` resources can create ELBs or `PersistentVolume` resources can create EBS volumes.

Various more and less standard alternatives are coming up for the general task of managing AWS resources through Kubernetes, but most are in their infancy:

- [Kubernetes RDS provisioner](https://github.com/sorenmat/k8s-rds): specific to Kubernetes and RDS, unofficial, beta
- [Crossplane](https://github.com/crossplaneio/stack-aws): specific to Kubernetes but not AWS, unofficial
- [AWS Service Broker](https://github.com/awslabs/aws-servicebroker/tree/master/docs): not specific to Kubernetes, wide scope, official from AWS
- [AWS Service Operator](https://github.com/aws/aws-service-operator-k8s): right scope, official from AWS and somewhat blessed from Kubernetes, they just started rewriting it from scratch.

**Comment by thewilkybarkid** [comment]
- Kubernetes RDS provisioner: too unstable
- Crossplane: might work, but appears very complex
- AWS Service Broker: might work, but appears very complex
- AWS Service Operator: sounds promising, but not yet usable

So, we'll go for Terraform.
