### ISSUE TITLE
Make articles dereferencable

### ISSUE THREAD

**Issue by thewilkybarkid** [libero/publisher#367]
Move articles from being a blank node inside the article list to being a dereferenceable link.

So instead of being like:

```json
{
  "@id": "http://localhost:8080/articles",
  "@type": "hydra:Collection",
  "hydra:member": {
    "@id": "_:2572c2a18498c6114a0f6cd14fd17c01"
  },
},
{
  "@id": "_:2572c2a18498c6114a0f6cd14fd17c01",
  "@type": "schema:Article",
  "schema:name": "My Article"
}
```

it's:

```json
{
  "@id": "http://localhost:8080/articles",
  "@type": "hydra:Collection",
  "hydra:member": {
    "@id": "http://localhost:8080/articles/2572c2a18498c6114a0f6cd14fd17c01"
  },
}
```

and the link is:

```json
{
  "@id": "http://localhost:8080/articles/2572c2a18498c6114a0f6cd14fd17c01",
  "@type": "schema:Article",
  "schema:name": "My Article"
}
```

Definition of Done:

- [x] Articles are dereferenceable resources

## Related

- The API documentation shouldn't need changing (already declared as a link).
- The router can't be used as the whole URL is the named node
  - The server [generates the named node on creation](https://github.com/libero/article-store/blob/5758e15e23b5023f583f2b6d7d9bfa7727c0c17b/src/routes/add-article.ts#L32)
  - Use the pattern `/articles/[some-unique-string]` for now
- Blocks https://github.com/libero/publisher/issues/292, https://github.com/libero/publisher/issues/357 (persist in a database).

## Tasks

- [x] Change from blank nodes to named nodes (https://github.com/libero/article-store/pull/181)
- [x] The `Location` header on the add article response is to the newly-created resource (https://github.com/libero/article-store/pull/184)
- [x] Add middleware to find and return an article (https://github.com/libero/article-store/pull/184)
- ~Update Hypertest~

**Comment by giorgiosironi** [comment]
A bit confused by the fact that the `Use the pattern /articles/[some-unique-string]` contrasts with the examples `@id` values containing a full IRI with the hostname. However it seems [hostnames are added at runtime](https://github.com/libero/article-store/blob/c5d59ae70c3469eee4f25a5bcb001ca3ec376e41/src/routes/article-list.ts#L19) so not a problem to continue doing that.
