### ISSUE TITLE
Spike for micro frontends architecture

### ISSUE THREAD

**Issue by giorgiosironi** [libero/publisher#371]
Determine if the Publisher frontend (that is the equivalent of eLife's Journal and the previous version's Browser) should be split into multiple services or not. The default position is to continue having a monolith.

Definition of Done:

- [x] Approach is agreed. (https://github.com/libero/publisher/pull/387)

## Related

- Blocks #372

## Tasks

- [x] Page-level routing (https://github.com/libero/publisher-micro-frontend-experiment/issues/2)
- [x] Assets and bundling (https://github.com/libero/publisher-micro-frontend-experiment/issues/3)
- [x] Performance (https://github.com/libero/publisher-micro-frontend-experiment/issues/4)
- [x] Sessions (https://github.com/libero/publisher-micro-frontend-experiment/issues/5)
- [x] Component-level integration (https://github.com/libero/publisher-micro-frontend-experiment/issues/6).

**Comment by thewilkybarkid** [comment]
Early thoughts:

Possible splits are by page, or by region (eg separate header and footer), or both. Client-side composition is a non-starter.

Benefits I can envisage:
- Can build up a site without having to resort to code/lots of config.
- Can replace bits as needed without throwing everything away (imaging unique 'About' sections, or things like eLife's Magazine or Labs).
- Can scale pages as needed (not that much of a problem though?)

Problems I can see:
- Asset handling if splitting by region (eg CSS/JS for the header combined with the rest of the page).
- Routing/URL generation between pages generated by different services.
- Unsure about relationship with hypermedia (does this compliment or complicated hypermedia usage?).
- Potential performance problems.

**Comment by thewilkybarkid** [comment]
Interesting slides: [Micro Frontends in the Wild](https://speakerdeck.com/squer/micro-frontends-in-the-wild).

**Comment by thewilkybarkid** [comment]
Push work so far at https://github.com/libero/publisher-micro-frontend-experiment

**Comment by thewilkybarkid** [comment]
I'm happy that the result of the spike and discussions has produced a viable plan. Next up: ADR.
