### ISSUE TITLE
Create Article Page

### ISSUE THREAD

**Issue by giorgiosironi** [libero/publisher#372]
Definition of Done:

- [x] New, empty, application is runnable.

## Related

- Requires decision following #371, and a suitable name.
- Blocks #373 (add the article page).

## Tasks

- [x] Create project (https://github.com/libero/article-page)
  - [x] Docker (https://github.com/libero/article-page/pull/1)
  - [x] TypeScript (https://github.com/libero/article-page/pull/2)
- [x] Create server (https://github.com/libero/article-page/pull/6)
- [x] Linting (https://github.com/libero/article-page/pull/4)
- [x] Testing (https://github.com/libero/article-page/pull/5)
