### ISSUE TITLE
Use default Kubernetes namespace

### ISSUE THREAD

**Issue by thewilkybarkid** [libero/publisher#377]
Definition of Done:

- [x] `publisher` namespace is removed in favour of `default`

## Related

Follows #363 (adds namespace usage to Terraform)

## Tasks

- [x] Decide on a namespace
- ~'Create', if needed, the namespace through Terraform~
- [x] Redeploy Publisher chart
- [x] Update External DNS namespace

**Comment by thewilkybarkid** [comment]
Decided to remove the namespace concept entirely (ie use `default`) in favour of Helm release names and labels.

**Comment by giorgiosironi** [comment]
To be precise, the chart supports namespace use, but our deployment doesn't use them.
