### ISSUE TITLE
Move infrastructure CI to GitHub Actions

### ISSUE THREAD

**Issue by thewilkybarkid** [libero/publisher#378]
Definition of Done:

- [ ] CI uses GitHub Actions rather than Travis CI

## Tasks

- [ ] Remove Travis configuration
- [ ] Add GitHub workflow
- [ ] Check scripts still make sense
