### ISSUE TITLE
Make ports customisable for development

### ISSUE THREAD

**Issue by thewilkybarkid** [libero/publisher#383]
Definition of Done:

- [ ] Can customise the port numbers

## Related

- Refs https://github.com/libero/article-store/pull/261#discussion_r388243691.

## Tasks

- [ ] Make app port customisable
- [ ] Make console port customisable

**Comment by giorgiosironi** [comment]
Any appropriate milestone?

**Comment by thewilkybarkid** [comment]
Not really... go for the same as https://github.com/libero/publisher/issues/374 though?
