### ISSUE TITLE
Allow Hypertest to be run through Make

### ISSUE THREAD

**Issue by thewilkybarkid** [libero/publisher#384]
Definition of Done:

- [x] Hypertest is run through Make rather than a GitHub Actions script

## Tasks

- [x] Create Make command (https://github.com/libero/article-store/pull/272)
- [x] Remove current script (https://github.com/libero/article-store/pull/272)
- [x] Update CI (https://github.com/libero/article-store/pull/272)
- [x] Document usage (https://github.com/libero/article-store/pull/272)
