### ISSUE TITLE
Deploy Article Page

### ISSUE THREAD

**Issue by thewilkybarkid** [libero/publisher#388]
Definition of Done:

- [x] Article Page is available

## Related

- Blocked by #372 

## Tasks

- [x] Push image to Docker Hub
- [x] Deploy Article Page
  - [x] `Deployment`
  - [x] `Service`
  - [x] `NOTES`
- ~Deploy a proxy (Nginx? Varnish?)~

**Comment by giorgiosironi** [comment]
Added a few details to the checklist.

**Comment by giorgiosironi** [comment]
http://publisher--test--article-page.libero.pub/ is there now. Do we want to add a proxy? Doesn't seem to be a particular big risk or high value with only one frontend in place.

**Comment by thewilkybarkid** [comment]
Might as well leave for now.
